### ISSUE TITLE
Runtime error: panic: oops, unexpected segment type: *ice.Segment

### ISSUE THREAD

**Issue by siddharthlatest** [blugelabs/ice#17]
I'm seeing this panic error when using Bluge (latest, 0.2.1) with Go 1.18.3 on a Linux / AMD64 architecture. I don't see the same on Mac / ARM64.

Stacktrace details:

```
panic: oops, unexpected segment type: *ice.Segment

goroutine 594 [running]:
github.com/blugelabs/ice/v2.merge({0xc002444ab0, 0x3, 0x7f1741100571?}, {0xc000c0a348, 0x3, 0x3}, {0x107d7a0, 0xc0021b8880}, 0xc0000c67a0?)
	/home/centos/go/pkg/mod/github.com/blugelabs/ice/v2@v2.0.1/merge.go:82 +0x179
github.com/blugelabs/ice/v2.(*Merger).WriteTo(0xc00021c910, {0x107e4c0?, 0xc0000c67a0?}, 0x7f16f88ba7ae?)
	/home/centos/go/pkg/mod/github.com/blugelabs/ice/v2@v2.0.1/merge.go:48 +0x153
github.com/blugelabs/bluge/index.(*FileSystemDirectory).Persist(0xc0023e4680, {0x7f16f88ba7ae, 0x4}, 0xc000c0a348?, {0x7f1750252d00, 0xc00021c910}, 0x100000?)
	/home/centos/go/pkg/mod/github.com/blugelabs/bluge@v0.2.1/index/directory_fs.go:125 +0x1bb
github.com/blugelabs/bluge/index.(*Writer).merge(0xc000c4e000, {0xc002444ab0?, 0xc00021c8c0?, 0x8?}, {0xc000c0a348?, 0xc000da9468?, 0xaaaaaaaaaaaaa?}, 0x2?)
	/home/centos/go/pkg/mod/github.com/blugelabs/bluge@v0.2.1/index/merge.go:368 +0xb5
github.com/blugelabs/bluge/index.(*Writer).executeMergeTask(0xc000c4e000, 0xc00298ea20, 0xc000c0a330)
	/home/centos/go/pkg/mod/github.com/blugelabs/bluge@v0.2.1/index/merge.go:144 +0x125
github.com/blugelabs/bluge/index.(*Writer).planMergeAtSnapshot(0xc000c4e000, 0xc000024001?, 0xc000456800, {0xa, 0x4c4b40, 0x4024000000000000, 0xa, 0x7d0, 0x4000000000000000, 0x0, ...})
	/home/centos/go/pkg/mod/github.com/blugelabs/bluge@v0.2.1/index/merge.go:118 +0x30b
github.com/blugelabs/bluge/index.(*Writer).mergerLoop(0xc000c4e000, 0x7f1713f1a5e6?, 0xc0011fa480?)
	/home/centos/go/pkg/mod/github.com/blugelabs/bluge@v0.2.1/index/merge.go:56 +0x257
created by github.com/blugelabs/bluge/index.OpenWriter
	/home/centos/go/pkg/mod/github.com/blugelabs/bluge@v0.2.1/index/writer.go:131 +0x83e
```

**Comment by mschoch** [comment]
Yes, the latest version is broken.
